# -*- coding: utf-8 -*-
"""
Created on Thu May 11 11:03:06 2017

@author: S.Y. Agustsson
"""

from PyQt5 import QtGui as qg  # (the example applies equally well to PySide)
from PyQt5 import QtWidgets as qw
from PyQt5 import QtCore as qc
import sys
import pyqtgraph as pg
import numpy as np
from functionlibrary import transient as tr
import qdarkstyle
import os
from GUI import TransientsWidgets as tw


def main():
    # used to see errors generated by PyQt5 in pycharm:
    sys._excepthook = sys.excepthook
    # Set the exception hook to our wrapping function
    sys.excepthook = my_exception_hook()

    app = qc.QCoreApplication.instance()
    if app is None:
        app = qw.QApplication(sys.argv)
    # Create handle prg for the Graphic Interface
    prg = tw.MainWindow()
    prg.show()

    try:
        app.exec_()
    except:
        print('exiting')


def my_exception_hook(exctype, value, traceback):
    # Print the error and traceback
    print(exctype, value, traceback)
    # Call the normal Exception hook after
    sys._excepthook(exctype, value, traceback)
    sys.exit(1)


if __name__ == '__main__':
    main()
